# -*- coding: utf-8 -*-
"""aicte.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B2HJnDlTfIpRe5JiucKQZJx9fH2DGGF-
"""

!pip install kaggle
from google.colab import files
files.upload()   # Choose kaggle.json from your computer
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!kaggle datasets download ryandpark/fruit-quality-classification -p /content
import zipfile
import os

zip_path = '/content/fruit-quality-classification.zip'
extract_path = '/content/FruitQualityDataset'

os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print(f"✅ Dataset extracted to: {extract_path}")

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Define paths
dataset_dir = '/content/FruitQualityDataset'
img_height, img_width = 224, 224 # Define image dimensions here
batch_size = 32

# Data augmentation for training
train_datagen = ImageDataGenerator(
    rescale=1./255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    validation_split=0.2)

train_generator = train_datagen.flow_from_directory(
    dataset_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='categorical',
    subset='training')

# Validation generator
validation_datagen = ImageDataGenerator(rescale=1./255, validation_split=0.2)

validation_generator = validation_datagen.flow_from_directory(
    dataset_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='categorical',
    subset='validation')

print("✅ Data generators created successfully.")

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.models import Model

# Define image dimensions
img_height, img_width = 224, 224

# Load pretrained MobileNetV2 (no top layer)
base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(img_height, img_width, 3))

x = base_model.output
x = GlobalAveragePooling2D()(x)

# Number of classes from dataset
num_classes = len(train_generator.class_indices)
predictions = Dense(num_classes, activation='softmax')(x)

# Final model
model = Model(inputs=base_model.input, outputs=predictions)

# Freeze base model
for layer in base_model.layers:
    layer.trainable = False

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

epochs = 10  # adjust if needed

history = model.fit(
    train_generator,
    steps_per_epoch=train_generator.samples // batch_size,
    epochs=epochs,
    validation_data=validation_generator,
    validation_steps=validation_generator.samples // batch_size)

print("✅ Model training completed.")
loss, accuracy = model.evaluate(validation_generator, steps=validation_generator.samples // batch_size)
print(f"✅ Model evaluation complete. Loss: {loss:.4f}, Accuracy: {accuracy:.4f}")

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.models import Model

# Load pretrained MobileNetV2 (no top layer)
base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(img_height, img_width, 3))

x = base_model.output
x = GlobalAveragePooling2D()(x)

# Number of classes from dataset
num_classes = len(train_generator.class_indices)
predictions = Dense(num_classes, activation='softmax')(x)

# Final model
model = Model(inputs=base_model.input, outputs=predictions)

# Freeze base model
for layer in base_model.layers:
    layer.trainable = False

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

model_save_path = '/content/fruit_quality_model.keras'
model.save(model_save_path)
print(f"✅ Model saved successfully to: {model_save_path}")

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report

# Get true labels and predictions for validation set
Y_true = validation_generator.classes
Y_pred = model.predict(validation_generator)
Y_pred_classes = np.argmax(Y_pred, axis=1)

# Confusion matrix
cm = confusion_matrix(Y_true, Y_pred_classes)
class_names = list(validation_generator.class_indices.keys())

plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=class_names, yticklabels=class_names)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

history = model.fit(
    train_generator,
    steps_per_epoch=train_generator.samples // batch_size,
    epochs=10,  # or the number you used earlier
    validation_data=validation_generator,
    validation_steps=validation_generator.samples // batch_size
)


# Print classification report
print("Classification Report:\n", classification_report(Y_true, Y_pred_classes, target_names=class_names))
# Accuracy plot
plt.figure(figsize=(8,6))
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.title("Model Accuracy")
plt.legend()
plt.show()

# Loss plot
plt.figure(figsize=(8,6))
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.title("Model Loss")
plt.legend()
plt.show()

from google.colab import files
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
from tensorflow.keras.preprocessing import image
import tensorflow as tf

# Load the trained model
model = tf.keras.models.load_model('/content/fruit_quality_model.keras')

# Class labels
class_labels = list(train_generator.class_indices.keys())

def predict_fruit(img_path):
    img = image.load_img(img_path, target_size=(224, 224))
    img_array = image.img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    predictions = model.predict(img_array)
    predicted_class = np.argmax(predictions, axis=1)[0]
    predicted_label = class_labels[predicted_class]

    print(f"✅ Prediction: {predicted_label} (confidence: {np.max(predictions)*100:.2f}%)")
    return predicted_label

# 🔹 Upload any image dynamically
uploaded = files.upload()

for filename in uploaded.keys():
    img_path = filename
    print(f"Image uploaded: {img_path}")

    # Predict
    predicted_label = predict_fruit(img_path)

    # Show image with prediction
    img = mpimg.imread(img_path)
    plt.imshow(img)
    plt.axis("off")
    plt.title(f"Prediction: {predicted_label}")
    plt.show()